// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpeQvtPA_EIt4m7JlcIQqzfn0K1BmaGZw',
    appId: '1:235451816763:web:88c59a323b96c478b2351e',
    messagingSenderId: '235451816763',
    projectId: 'todo-application-de835',
    authDomain: 'todo-application-de835.firebaseapp.com',
    storageBucket: 'todo-application-de835.firebasestorage.app',
    measurementId: 'G-VV16DX5NYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyUdC0OTS1qNfO-ndR6blULBb63G_OnA',
    appId: '1:235451816763:android:04b96169882359eeb2351e',
    messagingSenderId: '235451816763',
    projectId: 'todo-application-de835',
    storageBucket: 'todo-application-de835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGJTaQyoKurFPUXBC9D7rJGMB4CvntRA',
    appId: '1:235451816763:ios:8c0b53984b4490c3b2351e',
    messagingSenderId: '235451816763',
    projectId: 'todo-application-de835',
    storageBucket: 'todo-application-de835.firebasestorage.app',
    iosBundleId: 'com.sohail.todo',
  );
}
